name: MyActionDemo
run-name: ${{ github.actor }} testing actions
on: workflow_dispatch
jobs:
  MyTestJob:
    runs-on: macos-14
    steps:
      - run: echo "EVENT is ${{ github.event_name }}"
      - run: echo "RUNNER is ${{ runner.os }}"
      - run: echo "BRANCH is ${{ github.ref }} and REPO is ${{ github.repository }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ls -l ${{ github.workspace }}
      - run: brew list
      - run: brew info freetype
      - run: echo "STATUS ${{ job.status }}."
